name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_test_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: habit-tracker-frontend
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: habit-tracker-frontend/package-lock.json
      - name: Install frontend dependencies
        run: npm ci
      - name: check frontend style
        run: npm run lint
      - name: run build
        run: npm run build
      - name: run tests
        run: npm run test

  run_e2e_tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.61.0-noble
      env:
        HOME: /root
    steps:
      - uses: actions/checkout@v6
      # The e2e suite is run on a server resembling the production environment,
      # thus both frontend and backen dependencies are needed.
      - name: Install backend dependencies
        run: npm ci
        working-directory: backend
      - name: Install frontend dependencies
        run: npm ci
        working-directory: habit-tracker-frontend
      - name: run e2e tests
        run: npm run e2e
        working-directory: habit-tracker-frontend

  test_and_lint_backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: Install backend dependencies
        run: npm ci
      - name: check backend style
        run: npm run lint
      - name: run tests
        run: npm run test

  deploy:
    needs: [build_and_test_frontend, test_and_lint_backend, run_e2e_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment on render
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}

  tag_release:
    needs: [deploy]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          DRY_RUN: true
  
  success_notification:
    needs: [deploy]
    runs-on: ubuntu-latest
    if: ${{ needs.deploy.result == 'success' && github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip')}}
    steps:
      - uses: actions/checkout@v6
      - uses: sarisia/actions-status-discord@v1.16.0
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ needs.deploy.result }}
          content: ":white_check_mark: **Deployment Successful!** A new version deployed to production"
          title: "Deployment Details"
          nodetail: true
          notimestamp: true
          description: |
            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.actor }}
  
  failure_notification:
    needs:
      - build_and_test_frontend
      - test_and_lint_backend
      - deploy
      - tag_release
    runs-on: ubuntu-latest
    if: ${{ always() && !contains(join(github.event.commits.*.message, ' '), '#skip')}}
    steps:
      - name: Check if pipeline failed
        run: |
          echo "BUILD_FRONTEND=${{ needs.build_and_test_frontend.result }}"
          echo "TEST_BACKEND=${{ needs.test_and_lint_backend.result}}"
          echo "DEPLOY=${{ needs.deploy.result }}"
          echo "TAG=${{ needs.tag_release.result }}"

          if [ "${{ needs.build_and_test_frontend.result }}" = "failure" ] || \
            [ "${{ needs.deploy.result }}" = "failure" ] || \
            [ "${{ needs.test_and_lint_backend}}" = "failure" ] || \
            [ "${{ needs.tag_release.result }}" = "failure" ]; then
            echo "PIPELINE_FAILED=true" >> $GITHUB_ENV
          else
            echo "PIPELINE_FAILED=false" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@v6
      - name: Get commit message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%s)" >> $GITHUB_ENV
      
      - uses: sarisia/actions-status-discord@v1.16.0
        if: env.PIPELINE_FAILED == 'true'
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: failure
          content: ":x: **Pipeline Failed!** The pipeline encountered an error"
          title: "Failure Details"
          notimestamp: true
          nodetail: true
          description: |
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref_name }}
            **Commit:** ${{ github.sha }}
            **Message:** ${{ env.COMMIT_MESSAGE }}
            **Author:** ${{ github.actor }}
            **Workflow:** ${{ github.workflow }}
            **Jobs:**
              **Frontend build:** ${{ needs.build_and_test_frontend.result }}
              **Backend test:** ${{ needs.test_and_lint_backend.result }}
              **Deploy:** ${{ needs.deploy.result }}
              **Release:** ${{ needs.tag_release.result }}

            [view commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            [view commit](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})